added comment
avero-it/mediamogul pull request #1
Opened 2023-02-04 10:40 UTC by simobgl

one

2023-02-04 10:43 UTC, KaliMik85 approved these changes

2023-02-04 10:43 UTC, Geogufo approved these changes

2023-02-04 10:46 UTC, KaliMik85 commented
ok

2023-02-04 10:46 UTC, simobgl commented
> 

thanks

2023-02-04 10:47 UTC, Geogufo requested changes

2023-02-04 10:47 UTC, Geogufo commented on cmd/mmApi/main.go
> +	// comment
Incorrect

2023-02-04 10:48 UTC, simobgl commented on cmd/mmApi/main.go
> +	// comment
solved via 119903051680e4b822fd70afab42bcb36005e90e

2023-02-04 10:49 UTC, Geogufo approved these changes

2023-02-04 10:49 UTC, KaliMik85 approved these changes

2023-02-04 10:50 UTC, KaliMik85 approved these changes

2023-02-04 10:56 UTC, KaliMik85 approved these changes

2023-02-04 10:56 UTC, Geogufo approved these changes

2023-02-04 11:00 UTC, KaliMik85 approved these changes

2023-02-04 11:00 UTC, KaliMik85 approved these changes

2023-02-04 11:01 UTC, Geogufo approved these changes

2023-02-05 09:33 UTC, KaliMik85 commented
ok

2023-02-05 10:24 UTC, merged